---
version: 2
log-file: /tmp/efm.log
log-level: 1

lint-debounce: 1s

tools:
  # yaml-yamllint: &yaml-yamllint
  #   lint-command: 'yamllint -f parsable -'
  #   lint-stdin: true

  python-flake8: &python-flake8
    root-markers:
      - .venv/
    require-marker: true
    lint-command: '.venv/bin/flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  javascript-eslint: &javascript-eslint
    root-markers:
      - node_modules/
    require-marker: true
    lint-command: 'node_modules/eslint/bin/eslint.js -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

  dockerfile-hadolint: &dockerfile-hadolint
    lint-command: 'hadolint --no-color'
    lint-formats:
      - '%f:%l %m'

languages:
  # yaml:
  #   - <<: *yaml-yamllint

  python:
    - <<: *python-flake8

  dockerfile:
    - <<: *dockerfile-hadolint

  javascript:
    - <<: *javascript-eslint

  vue:
    - <<: *javascript-eslint
