version: 2
log-file: /tmp/efm.log
log-level: 1

root-markers:
  - node_modules/
  - .git/
lint-debounce: 1s

tools:
  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  python-flake8: &python-flake8
    # lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-command: '.venv/bin/flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  javascript-eslint: &javascript-eslint
    # lint-command: 'eslint -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-command: 'node_modules/eslint/bin/eslint.js -f visualstudio --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - "%f(%l,%c): %tarning %m"
      - "%f(%l,%c): %rror %m"

languages:
  yaml:
    - <<: *yaml-yamllint

  python:
    - <<: *python-flake8

  javascript:
    - <<: *javascript-eslint

  vue:
    - <<: *javascript-eslint
